DROP DATABASE IF EXISTS newsfeed_db;

CREATE DATABASE newsfeed_db;

CREATE TABLE login(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL
);
